/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View.Return;

import Model.BookedCar;
import Model.Client;
import Model.Staff;
import Controller.Return.ContractController;
import Model.Contract;
import Model.ContractWarrant;
import java.util.ArrayList;
import javax.swing.JLabel;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.JTextField;

/**
 *
 * @author LEGION
 */
public class ContractViewFrm extends javax.swing.JFrame {

    private ArrayList<BookedCar> bc = new ArrayList<>();
    private ArrayList<ContractWarrant> cw = new ArrayList<>();
    private Client client;
    private Staff staff;

    public ContractViewFrm(Client client, Staff staff, ArrayList<BookedCar> bc, ArrayList<ContractWarrant> cw) {
        initComponents();
        setLocationRelativeTo(null);
        this.bc = bc;
        this.cw = cw;
        this.client = client;
        this.staff = staff;
        ContractController a = new ContractController(this);
        a.init();
    }

    public ContractViewFrm(Client client, Staff staff, ArrayList<BookedCar> bc) {
        initComponents();
        setLocationRelativeTo(null);
        this.bc = bc;
        this.client = client;
        this.staff = staff;
        ContractController a = new ContractController(this);
        a.init();
    }

    /**
     * Creates new form ContractViewFrm
     */
    public ContractViewFrm() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        titleLabel = new javax.swing.JLabel();
        dateLabel = new javax.swing.JLabel();
        date = new javax.swing.JLabel();
        carLabel = new javax.swing.JLabel();
        carScrollPane = new javax.swing.JScrollPane();
        carTable = new javax.swing.JTable();
        warrantLabel = new javax.swing.JLabel();
        warrantScrollPane = new javax.swing.JScrollPane();
        warrantTable = new javax.swing.JTable();
        staffName = new javax.swing.JLabel();
        staffLabel1 = new javax.swing.JLabel();
        clientLabel2 = new javax.swing.JLabel();
        clientName = new javax.swing.JLabel();
        depositLabel = new javax.swing.JLabel();
        total = new javax.swing.JLabel();
        totalLabel = new javax.swing.JLabel();
        deposit = new javax.swing.JLabel();
        backLabel = new javax.swing.JLabel();
        viewBillLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        titleLabel.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        titleLabel.setText("View Contract");

        dateLabel.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        dateLabel.setText("Booking Date:");

        date.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        date.setText("Date");

        carLabel.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        carLabel.setText("Booked Car List:");

        carTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Name", "Received Date", "Return Date", "Total Price"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        carScrollPane.setViewportView(carTable);

        warrantLabel.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        warrantLabel.setText("Warrant List:");

        warrantTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Check In", "Check Out", "Type", "Value", "Description"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        warrantScrollPane.setViewportView(warrantTable);
        if (warrantTable.getColumnModel().getColumnCount() > 0) {
            warrantTable.getColumnModel().getColumn(4).setResizable(false);
        }

        staffName.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        staffName.setText("Staff Name");

        staffLabel1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        staffLabel1.setText("Staff:");

        clientLabel2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        clientLabel2.setText("Client:");

        clientName.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        clientName.setText("Client Name");

        depositLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        depositLabel.setText("Deposit:");

        total.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        total.setText("...");

        totalLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        totalLabel.setText("Total:");

        deposit.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        deposit.setText("...");

        backLabel.setText("Back");

        viewBillLabel.setText("View Bill");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(warrantLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(clientLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(clientName, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(146, 146, 146)
                                .addComponent(staffLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(staffName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(warrantScrollPane, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(carScrollPane, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(depositLabel)
                                            .addComponent(totalLabel, javax.swing.GroupLayout.Alignment.TRAILING))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(deposit, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(total, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 299, Short.MAX_VALUE)
                                                .addComponent(viewBillLabel))))
                                    .addComponent(carLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(dateLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(date, javax.swing.GroupLayout.PREFERRED_SIZE, 427, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(20, 20, 20)))
                        .addGap(30, 30, 30))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(titleLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(backLabel)
                        .addGap(40, 40, 40))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(titleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(backLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dateLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(date, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(clientLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(clientName, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(staffLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(staffName, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(carLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(carScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(warrantLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(warrantScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(depositLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(deposit, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(totalLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(total, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(14, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(viewBillLabel)
                        .addGap(43, 43, 43))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @return
     */
    public ArrayList<BookedCar> getBc() {
        return bc;
    }

    public void setBc(ArrayList<BookedCar> bc) {
        this.bc = bc;
    }

    public ArrayList<ContractWarrant> getCw() {
        return cw;
    }

    public void setCw(ArrayList<ContractWarrant> cw) {
        this.cw = cw;
    }

    public Client getClient() {
        return client;
    }

    public void setClient(Client client) {
        this.client = client;
    }

    public Staff getStaff() {
        return staff;
    }

    public void setStaff(Staff staff) {
        this.staff = staff;
    }

    public JLabel getCarLabel() {
        return carLabel;
    }

    public void setCarLabel(JLabel carLabel) {
        this.carLabel = carLabel;
    }

    public JScrollPane getCarScrollPane() {
        return carScrollPane;
    }

    public void setCarScrollPane(JScrollPane carScrollPane) {
        this.carScrollPane = carScrollPane;
    }

    public JTable getCarTable() {
        return carTable;
    }

    public void setCarTable(JTable carTable) {
        this.carTable = carTable;
    }

    public JLabel getClientLabel2() {
        return clientLabel2;
    }

    public void setClientLabel2(JLabel clientLabel2) {
        this.clientLabel2 = clientLabel2;
    }

    public JLabel getClientName() {
        return clientName;
    }

    public void setClientName(JLabel clientName) {
        this.clientName = clientName;
    }

    public JLabel getViewBillLabel() {
        return viewBillLabel;
    }

    public void getViewBillLabel(JLabel viewBillLabel) {
        this.viewBillLabel = viewBillLabel;
    }

    public JLabel getDateLabel() {
        return dateLabel;
    }

    public void setDateLabel(JLabel dateLabel) {
        this.dateLabel = dateLabel;
    }

    public JLabel getDeposit() {
        return deposit;
    }

    public void setDeposit(JLabel deposit) {
        this.deposit = deposit;
    }

    public JLabel getDepositLabel() {
        return depositLabel;
    }

    public void setDepositLabel(JLabel depositLabel) {
        this.depositLabel = depositLabel;
    }

    public JLabel getDate() {
        return date;
    }

    public void setDate(JLabel date) {
        this.date = date;
    }

    public JLabel getStaffLabel1() {
        return staffLabel1;
    }

    public void setStaffLabel1(JLabel staffLabel1) {
        this.staffLabel1 = staffLabel1;
    }

    public JLabel getStaffName() {
        return staffName;
    }

    public void setStaffName(JLabel staffName) {
        this.staffName = staffName;
    }

    public JLabel getTitleLabel() {
        return titleLabel;
    }

    public void setTitleLabel(JLabel titleLabel) {
        this.titleLabel = titleLabel;
    }

    public JLabel getTotal() {
        return total;
    }

    public void setTotal(JLabel total) {
        this.total = total;
    }

    public JLabel getTotalLabel() {
        return totalLabel;
    }

    public void setTotalLabel(JLabel totalLabel) {
        this.totalLabel = totalLabel;
    }

    public JLabel getWarrantLabel() {
        return warrantLabel;
    }

    public void setWarrantLabel(JLabel warrantLabel) {
        this.warrantLabel = warrantLabel;
    }

    public JScrollPane getWarrantScrollPane() {
        return warrantScrollPane;
    }

    public void setWarrantScrollPane(JScrollPane warrantScrollPane) {
        this.warrantScrollPane = warrantScrollPane;
    }

    public JTable getWarrantTable() {
        return warrantTable;
    }

    public void setWarrantTable(JTable warrantTable) {
        this.warrantTable = warrantTable;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel backLabel;
    private javax.swing.JLabel carLabel;
    private javax.swing.JScrollPane carScrollPane;
    private javax.swing.JTable carTable;
    private javax.swing.JLabel clientLabel2;
    private javax.swing.JLabel clientName;
    private javax.swing.JLabel date;
    private javax.swing.JLabel dateLabel;
    private javax.swing.JLabel deposit;
    private javax.swing.JLabel depositLabel;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JLabel staffLabel1;
    private javax.swing.JLabel staffName;
    private javax.swing.JLabel titleLabel;
    private javax.swing.JLabel total;
    private javax.swing.JLabel totalLabel;
    private javax.swing.JLabel viewBillLabel;
    private javax.swing.JLabel warrantLabel;
    private javax.swing.JScrollPane warrantScrollPane;
    private javax.swing.JTable warrantTable;
    // End of variables declaration//GEN-END:variables
}
