/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View.login;

import Model.Staff;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import view.Return.SearchContractFrm;

/**
 *
 * @author Lemony
 */
public class CashierHomeFrm extends javax.swing.JFrame implements ActionListener{
    private final Staff s; 
    /**
     * Creates new form cashierHomeFrm
     * @param s
     */
    public CashierHomeFrm(Staff s) {
        super("Cashier Home");
        initComponents();
        this.s = s;
        logstatlbl.setText("Logged as " + s.getName());
        setLocationRelativeTo(null);
        setResizable(false);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        titlelbl = new javax.swing.JLabel();
        logstatlbl = new javax.swing.JLabel();
        recieveBtn = new javax.swing.JButton();
        logoutBtn = new javax.swing.JButton();
        logoutLabel = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        titlelbl.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        titlelbl.setText("Cashier Home ");

        logstatlbl.setText("Loged as");

        recieveBtn.setText("Receive Car");
        recieveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                recieveBtnActionPerformed(evt);
            }
        });

        logoutBtn.setText("logout");
        logoutBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutBtnActionPerformed(evt);
            }
        });

        logoutLabel.setText("logout");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(logstatlbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(logoutLabel)
                .addGap(26, 26, 26)
                .addComponent(logoutBtn)
                .addGap(17, 17, 17))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(163, 163, 163)
                        .addComponent(recieveBtn))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(86, 86, 86)
                        .addComponent(titlelbl)))
                .addContainerGap(94, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(logstatlbl)
                    .addComponent(logoutBtn)
                    .addComponent(logoutLabel))
                .addGap(29, 29, 29)
                .addComponent(titlelbl)
                .addGap(44, 44, 44)
                .addComponent(recieveBtn)
                .addContainerGap(36, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void recieveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_recieveBtnActionPerformed
        new SearchContractFrm(s).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_recieveBtnActionPerformed

    private void logoutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutBtnActionPerformed
        new Login().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_logoutBtnActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String[] args) {
//        Login myFrame = new CashierHomeFrm().setVisible(true);
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton logoutBtn;
    private javax.swing.JLabel logoutLabel;
    private javax.swing.JLabel logstatlbl;
    private javax.swing.JButton recieveBtn;
    private javax.swing.JLabel titlelbl;
    // End of variables declaration//GEN-END:variables

    @Override
    public void actionPerformed(ActionEvent e) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

}
