/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View.Rental;

import Model.Contract;
import Controller.Rental.BillController;
import Model.Staff;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JTextField;
import keeptoo.KButton;
import keeptoo.KGradientPanel;

/**
 *
 * @author LEGION
 */
public class BillViewFrm extends javax.swing.JFrame {

    private Contract contract;
    private Staff staff;
    private float deposit;
    public BillViewFrm(Contract contract,Staff staff,float deposit) {
        initComponents();
        this.contract = contract;
        this.staff = staff;
        this.deposit = deposit;
        BillController a = new BillController(this);
        a.init();
    }

    public float getDeposit() {
        return deposit;
    }

    public void setDeposit(float deposit) {
        this.deposit = deposit;
    }

    /**
     * Creates new form BillViewFrm
     */
    public BillViewFrm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgPanel = new keeptoo.KGradientPanel();
        jPanel1 = new javax.swing.JPanel();
        clientName = new javax.swing.JTextField();
        date = new javax.swing.JTextField();
        note = new javax.swing.JTextField();
        titleLabel = new javax.swing.JLabel();
        clientLabel = new javax.swing.JLabel();
        dateLabel = new javax.swing.JLabel();
        noteLabel = new javax.swing.JLabel();
        penaltyLabel = new javax.swing.JLabel();
        penalty = new javax.swing.JTextField();
        paymentTypeLabel = new javax.swing.JLabel();
        paymentType = new javax.swing.JComboBox<>();
        addBtt = new keeptoo.KButton();
        backBtt = new keeptoo.KButton();
        logoImage = new javax.swing.JLabel();
        logoLabel = new javax.swing.JLabel();
        penaltyLabel1 = new javax.swing.JLabel();
        penalty1 = new javax.swing.JTextField();
        staffLabel = new javax.swing.JLabel();
        staffField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(102, 102, 102));

        clientName.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        clientName.setForeground(new java.awt.Color(102, 102, 102));
        clientName.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(12, 91, 160)));
        clientName.setDisabledTextColor(new java.awt.Color(255, 255, 255));

        date.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        date.setForeground(new java.awt.Color(102, 102, 102));
        date.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(12, 91, 160)));
        date.setDisabledTextColor(new java.awt.Color(255, 255, 255));

        note.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        note.setForeground(new java.awt.Color(102, 102, 102));
        note.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(12, 91, 160)));

        titleLabel.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        titleLabel.setForeground(new java.awt.Color(12, 91, 160));
        titleLabel.setText("Bill");

        clientLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        clientLabel.setForeground(new java.awt.Color(12, 91, 160));
        clientLabel.setText("Client");

        dateLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        dateLabel.setForeground(new java.awt.Color(12, 91, 160));
        dateLabel.setText("Payment Date");

        noteLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        noteLabel.setForeground(new java.awt.Color(12, 91, 160));
        noteLabel.setText("Note");

        penaltyLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        penaltyLabel.setForeground(new java.awt.Color(12, 91, 160));
        penaltyLabel.setText("Penalty");

        penalty.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        penalty.setForeground(new java.awt.Color(102, 102, 102));
        penalty.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(12, 91, 160)));
        penalty.setDisabledTextColor(new java.awt.Color(255, 255, 255));

        paymentTypeLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        paymentTypeLabel.setForeground(new java.awt.Color(12, 91, 160));
        paymentTypeLabel.setText("Payment Type");

        paymentType.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        paymentType.setForeground(new java.awt.Color(102, 102, 255));
        paymentType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cash", "Debit", "Credit", "Payment Plan" }));

        addBtt.setBorder(null);
        addBtt.setText("Continue");
        addBtt.setkBorderRadius(30);
        addBtt.setkEndColor(new java.awt.Color(255, 0, 255));
        addBtt.setkHoverEndColor(new java.awt.Color(255, 255, 255));
        addBtt.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        addBtt.setkHoverStartColor(new java.awt.Color(102, 255, 102));
        addBtt.setkStartColor(new java.awt.Color(12, 91, 160));

        backBtt.setBorder(null);
        backBtt.setText("Cancel");
        backBtt.setkBorderRadius(30);
        backBtt.setkEndColor(new java.awt.Color(255, 0, 255));
        backBtt.setkHoverEndColor(new java.awt.Color(255, 255, 255));
        backBtt.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        backBtt.setkHoverStartColor(new java.awt.Color(102, 255, 102));
        backBtt.setkStartColor(new java.awt.Color(12, 91, 160));

        logoImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Rental/Icon/f1_car_60px_black.png"))); // NOI18N
        logoImage.setMaximumSize(new java.awt.Dimension(50, 50));
        logoImage.setMinimumSize(new java.awt.Dimension(50, 50));

        logoLabel.setFont(new java.awt.Font("Segoe Print", 1, 24)); // NOI18N
        logoLabel.setForeground(new java.awt.Color(0, 0, 0));
        logoLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        logoLabel.setText("ALT F4 Rental");

        penaltyLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        penaltyLabel1.setForeground(new java.awt.Color(12, 91, 160));
        penaltyLabel1.setText("Total");

        penalty1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        penalty1.setForeground(new java.awt.Color(102, 102, 102));
        penalty1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(12, 91, 160)));
        penalty1.setDisabledTextColor(new java.awt.Color(255, 255, 255));

        staffLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        staffLabel.setForeground(new java.awt.Color(12, 91, 160));
        staffLabel.setText("Staff");

        staffField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        staffField.setForeground(new java.awt.Color(102, 102, 102));
        staffField.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(12, 91, 160)));
        staffField.setDisabledTextColor(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addComponent(titleLabel)
                .addGap(61, 61, 61)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(logoImage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(logoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addComponent(clientLabel))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addComponent(dateLabel))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addComponent(date, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addComponent(noteLabel))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addComponent(note, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addComponent(penaltyLabel))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(addBtt, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(backBtt, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(paymentTypeLabel)
                    .addComponent(paymentType, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(penaltyLabel1)
                            .addComponent(penalty1, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(penalty, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(staffLabel)
                        .addComponent(staffField, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(clientName, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(titleLabel))
                    .addComponent(logoImage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(logoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(11, 11, 11)
                .addComponent(clientLabel)
                .addGap(6, 6, 6)
                .addComponent(clientName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(staffLabel)
                .addGap(6, 6, 6)
                .addComponent(staffField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addComponent(dateLabel)
                .addGap(6, 6, 6)
                .addComponent(date, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(noteLabel)
                .addGap(6, 6, 6)
                .addComponent(note, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(penaltyLabel)
                .addGap(6, 6, 6)
                .addComponent(penalty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(penaltyLabel1)
                .addGap(10, 10, 10)
                .addComponent(penalty1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(paymentTypeLabel)
                .addGap(10, 10, 10)
                .addComponent(paymentType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(addBtt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(backBtt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(63, 63, 63))
        );

        javax.swing.GroupLayout bgPanelLayout = new javax.swing.GroupLayout(bgPanel);
        bgPanel.setLayout(bgPanelLayout);
        bgPanelLayout.setHorizontalGroup(
            bgPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgPanelLayout.createSequentialGroup()
                .addGap(115, 115, 115)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(115, 115, 115))
        );
        bgPanelLayout.setVerticalGroup(
            bgPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgPanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(bgPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 660, 740));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Metal".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BillViewFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BillViewFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BillViewFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BillViewFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BillViewFrm().setVisible(true);
            }
        });
    }

    public Staff getStaff() {
        return staff;
    }

    public void setStaff(Staff staff) {
        this.staff = staff;
    }

    public Contract getContract() {
        return contract;
    }

    public void setContract(Contract contract) {
        this.contract = contract;
    }

    public JLabel getTitleLabel() {
        return titleLabel;
    }

    public void setTitleLabel(JLabel titleLabel) {
        this.titleLabel = titleLabel;
    }



    public KButton getAddBtt() {
        return addBtt;
    }

    public void setAddBtt(KButton addBtt) {
        this.addBtt = addBtt;
    }

    public KButton getBackBtt() {
        return backBtt;
    }

    public void setBackBtt(KButton backBtt) {
        this.backBtt = backBtt;
    }

    public KGradientPanel getBgPanel() {
        return bgPanel;
    }

    public void setBgPanel(KGradientPanel bgPanel) {
        this.bgPanel = bgPanel;
    }

    public JLabel getClientLabel() {
        return clientLabel;
    }

    public void setClientLabel(JLabel clientLabel) {
        this.clientLabel = clientLabel;
    }

    public JTextField getClientName() {
        return clientName;
    }

    public void setClientName(JTextField clientName) {
        this.clientName = clientName;
    }

    public JTextField getDate() {
        return date;
    }

    public void setDate(JTextField date) {
        this.date = date;
    }

    public JLabel getDateLabel() {
        return dateLabel;
    }

    public void setDateLabel(JLabel dateLabel) {
        this.dateLabel = dateLabel;
    }

    public JPanel getjPanel1() {
        return jPanel1;
    }

    public void setjPanel1(JPanel jPanel1) {
        this.jPanel1 = jPanel1;
    }

    public JLabel getLogoImage() {
        return logoImage;
    }

    public void setLogoImage(JLabel logoImage) {
        this.logoImage = logoImage;
    }

    public JLabel getLogoLabel() {
        return logoLabel;
    }

    public void setLogoLabel(JLabel logoLabel) {
        this.logoLabel = logoLabel;
    }

    public JComboBox<String> getPaymentType() {
        return paymentType;
    }

    public void setPaymentType(JComboBox<String> paymentType) {
        this.paymentType = paymentType;
    }

    public JLabel getPaymentTypeLabel() {
        return paymentTypeLabel;
    }

    public void setPaymentTypeLabel(JLabel paymentTypeLabel) {
        this.paymentTypeLabel = paymentTypeLabel;
    }

    public JTextField getPenalty() {
        return penalty;
    }

    public void setPenalty(JTextField penalty) {
        this.penalty = penalty;
    }


    public JTextField getTotal() {
        return penalty1;
    }

    public void setTotal(JTextField total) {
        this.penalty1 = total;
    }

    public JLabel getTotalLabel() {
        return penaltyLabel1;
    }

    public void setTotalLabel(JLabel totalLabel) {
        this.penaltyLabel1 = totalLabel;
    }


    public JTextField getStaffField() {
        return staffField;
    }

    public void setStaffField(JTextField staffField) {
        this.staffField = staffField;
    }

    public JLabel getStaffLabel() {
        return staffLabel;
    }

    public void setStaffLabel(JLabel staffLabel) {
        this.staffLabel = staffLabel;
    }


    public JTextField getNote() {
        return note;
    }

    public void setNote(JTextField note) {
        this.note = note;
    }

    public JLabel getNoteLabel() {
        return noteLabel;
    }

    public void setNoteLabel(JLabel noteLabel) {
        this.noteLabel = noteLabel;
    }


    public JLabel getPenaltyLabel() {
        return penaltyLabel;
    }

    public void setPenaltyLabel(JLabel penaltyLabel) {
        this.penaltyLabel = penaltyLabel;
    }





    // Variables declaration - do not modify//GEN-BEGIN:variables
    private keeptoo.KButton addBtt;
    private keeptoo.KButton backBtt;
    private keeptoo.KGradientPanel bgPanel;
    private javax.swing.JLabel clientLabel;
    private javax.swing.JTextField clientName;
    private javax.swing.JTextField date;
    private javax.swing.JLabel dateLabel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel logoImage;
    private javax.swing.JLabel logoLabel;
    private javax.swing.JTextField note;
    private javax.swing.JLabel noteLabel;
    private javax.swing.JComboBox<String> paymentType;
    private javax.swing.JLabel paymentTypeLabel;
    private javax.swing.JTextField penalty;
    private javax.swing.JTextField penalty1;
    private javax.swing.JLabel penaltyLabel;
    private javax.swing.JLabel penaltyLabel1;
    private javax.swing.JTextField staffField;
    private javax.swing.JLabel staffLabel;
    private javax.swing.JLabel titleLabel;
    // End of variables declaration//GEN-END:variables
}
