/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View.Rental;

/**
 *
 * @author LEGION
 */
public class NewJFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgPanel = new keeptoo.KGradientPanel();
        titlePanel = new keeptoo.KGradientPanel();
        receivedDateLabel = new javax.swing.JLabel();
        returnDateLabel = new javax.swing.JLabel();
        typeLabel = new javax.swing.JLabel();
        classLabel = new javax.swing.JLabel();
        carType = new javax.swing.JComboBox<>();
        carClass = new javax.swing.JComboBox<>();
        nameLabel = new javax.swing.JLabel();
        nameField = new javax.swing.JTextField();
        pageLabel = new javax.swing.JLabel();
        pageField = new javax.swing.JTextField();
        receivedDate = new com.github.lgooddatepicker.components.DateTimePicker();
        returnDate = new com.github.lgooddatepicker.components.DateTimePicker();
        logoLabel = new javax.swing.JLabel();
        logoImage = new javax.swing.JLabel();
        backwardBtt = new keeptoo.KButton();
        logoutSide = new javax.swing.JPanel();
        icon3 = new javax.swing.JLabel();
        logoutText = new javax.swing.JLabel();
        forwardBtt = new keeptoo.KButton();
        jumpBtt = new keeptoo.KButton();
        searchBtt = new keeptoo.KButton();
        confirmBtt = new keeptoo.KButton();
        carCatalogPanel = new javax.swing.JPanel();
        cartScrollPane = new javax.swing.JScrollPane();
        cartPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bgPanel.setkEndColor(new java.awt.Color(93, 47, 208));
        bgPanel.setkStartColor(new java.awt.Color(183, 219, 230));
        bgPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        titlePanel.setkEndColor(new java.awt.Color(93, 47, 208));
        titlePanel.setkStartColor(new java.awt.Color(47, 24, 107));
        titlePanel.setPreferredSize(new java.awt.Dimension(1112, 200));
        titlePanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        receivedDateLabel.setBackground(new java.awt.Color(255, 255, 255));
        receivedDateLabel.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        receivedDateLabel.setForeground(new java.awt.Color(255, 255, 255));
        receivedDateLabel.setText("Received Date");
        titlePanel.add(receivedDateLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(298, 12, -1, -1));

        returnDateLabel.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        returnDateLabel.setForeground(new java.awt.Color(255, 255, 255));
        returnDateLabel.setText("Return Date");
        titlePanel.add(returnDateLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(298, 57, 127, -1));

        typeLabel.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        typeLabel.setForeground(new java.awt.Color(255, 255, 255));
        typeLabel.setText("Type");
        titlePanel.add(typeLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(694, 14, 50, -1));

        classLabel.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        classLabel.setForeground(new java.awt.Color(255, 255, 255));
        classLabel.setText("Class");
        titlePanel.add(classLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(694, 68, -1, -1));

        carType.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        carType.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        titlePanel.add(carType, new org.netbeans.lib.awtextra.AbsoluteConstraints(776, 66, 148, -1));

        carClass.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        carClass.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        titlePanel.add(carClass, new org.netbeans.lib.awtextra.AbsoluteConstraints(776, 12, 148, -1));

        nameLabel.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        nameLabel.setForeground(new java.awt.Color(255, 255, 255));
        nameLabel.setText("Name");
        titlePanel.add(nameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 110, -1, -1));

        nameField.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        titlePanel.add(nameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 110, 140, -1));

        pageLabel.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        pageLabel.setForeground(new java.awt.Color(255, 255, 255));
        pageLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pageLabel.setText("0/0");
        titlePanel.add(pageLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(107, 156, 58, 31));

        pageField.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        titlePanel.add(pageField, new org.netbeans.lib.awtextra.AbsoluteConstraints(334, 161, 54, -1));
        titlePanel.add(receivedDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(437, 14, -1, -1));
        titlePanel.add(returnDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(437, 57, -1, -1));

        logoLabel.setFont(new java.awt.Font("Segoe Print", 1, 24)); // NOI18N
        logoLabel.setForeground(new java.awt.Color(255, 255, 255));
        logoLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        logoLabel.setText("ALT F4 Rental");
        titlePanel.add(logoLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 280, 60));

        logoImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Rental/Icon/f1_car_60px.png"))); // NOI18N
        logoImage.setMaximumSize(new java.awt.Dimension(50, 50));
        logoImage.setMinimumSize(new java.awt.Dimension(50, 50));
        titlePanel.add(logoImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, 60));

        backwardBtt.setBorder(null);
        backwardBtt.setText(">");
        backwardBtt.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        backwardBtt.setkBorderRadius(30);
        backwardBtt.setkHoverForeGround(new java.awt.Color(255, 255, 0));
        backwardBtt.setMaximumSize(new java.awt.Dimension(49, 32));
        backwardBtt.setMinimumSize(new java.awt.Dimension(49, 32));
        backwardBtt.setPreferredSize(new java.awt.Dimension(49, 32));
        titlePanel.add(backwardBtt, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 150, 70, 40));

        logoutSide.setBackground(new java.awt.Color(93, 47, 208));
        logoutSide.setMinimumSize(new java.awt.Dimension(60, 60));
        logoutSide.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        icon3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Rental/Icon/exit_30px.png"))); // NOI18N
        logoutSide.add(icon3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 50, 60));

        logoutText.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        logoutText.setForeground(new java.awt.Color(255, 255, 255));
        logoutText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        logoutText.setText("Back to Login");
        logoutSide.add(logoutText, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 280, 60));

        titlePanel.add(logoutSide, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 0, -1, -1));

        forwardBtt.setBorder(null);
        forwardBtt.setText("<");
        forwardBtt.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        forwardBtt.setkBorderRadius(30);
        forwardBtt.setMaximumSize(new java.awt.Dimension(49, 32));
        forwardBtt.setMinimumSize(new java.awt.Dimension(49, 32));
        forwardBtt.setPreferredSize(new java.awt.Dimension(49, 32));
        titlePanel.add(forwardBtt, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, 70, 40));

        jumpBtt.setBorder(null);
        jumpBtt.setText("Jump");
        jumpBtt.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jumpBtt.setkBorderRadius(30);
        jumpBtt.setMaximumSize(new java.awt.Dimension(49, 32));
        jumpBtt.setMinimumSize(new java.awt.Dimension(49, 32));
        jumpBtt.setPreferredSize(new java.awt.Dimension(49, 32));
        titlePanel.add(jumpBtt, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 150, 70, 40));

        searchBtt.setBorder(null);
        searchBtt.setText("Search");
        searchBtt.setkBorderRadius(30);
        titlePanel.add(searchBtt, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 150, 130, -1));

        confirmBtt.setBorder(null);
        confirmBtt.setText("Confirm");
        confirmBtt.setkBorderRadius(30);
        confirmBtt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmBttActionPerformed(evt);
            }
        });
        titlePanel.add(confirmBtt, new org.netbeans.lib.awtextra.AbsoluteConstraints(1150, 150, 130, -1));

        bgPanel.add(titlePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1300, -1));

        carCatalogPanel.setBackground(new java.awt.Color(255, 255, 255));
        carCatalogPanel.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        carCatalogPanel.setMaximumSize(new java.awt.Dimension(851, 470));
        carCatalogPanel.setMinimumSize(new java.awt.Dimension(851, 470));

        javax.swing.GroupLayout carCatalogPanelLayout = new javax.swing.GroupLayout(carCatalogPanel);
        carCatalogPanel.setLayout(carCatalogPanelLayout);
        carCatalogPanelLayout.setHorizontalGroup(
            carCatalogPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 894, Short.MAX_VALUE)
        );
        carCatalogPanelLayout.setVerticalGroup(
            carCatalogPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 554, Short.MAX_VALUE)
        );

        bgPanel.add(carCatalogPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 900, 560));

        cartScrollPane.setBackground(new java.awt.Color(255, 255, 255));
        cartScrollPane.setViewportBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        cartScrollPane.setMinimumSize(new java.awt.Dimension(281, 470));
        cartScrollPane.setPreferredSize(new java.awt.Dimension(281, 470));

        cartPanel.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout cartPanelLayout = new javax.swing.GroupLayout(cartPanel);
        cartPanel.setLayout(cartPanelLayout);
        cartPanelLayout.setHorizontalGroup(
            cartPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 346, Short.MAX_VALUE)
        );
        cartPanelLayout.setVerticalGroup(
            cartPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 560, Short.MAX_VALUE)
        );

        cartScrollPane.setViewportView(cartPanel);

        bgPanel.add(cartScrollPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 210, 340, 560));

        getContentPane().add(bgPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1300, 790));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void confirmBttActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmBttActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_confirmBttActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private keeptoo.KButton backwardBtt;
    private keeptoo.KGradientPanel bgPanel;
    private javax.swing.JPanel carCatalogPanel;
    private javax.swing.JComboBox<String> carClass;
    private javax.swing.JComboBox<String> carType;
    private javax.swing.JPanel cartPanel;
    private javax.swing.JScrollPane cartScrollPane;
    private javax.swing.JLabel classLabel;
    private keeptoo.KButton confirmBtt;
    private keeptoo.KButton forwardBtt;
    private javax.swing.JLabel icon3;
    private keeptoo.KButton jumpBtt;
    private javax.swing.JLabel logoImage;
    private javax.swing.JLabel logoLabel;
    private javax.swing.JPanel logoutSide;
    private javax.swing.JLabel logoutText;
    private javax.swing.JTextField nameField;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JTextField pageField;
    private javax.swing.JLabel pageLabel;
    private com.github.lgooddatepicker.components.DateTimePicker receivedDate;
    private javax.swing.JLabel receivedDateLabel;
    private com.github.lgooddatepicker.components.DateTimePicker returnDate;
    private javax.swing.JLabel returnDateLabel;
    private keeptoo.KButton searchBtt;
    private keeptoo.KGradientPanel titlePanel;
    private javax.swing.JLabel typeLabel;
    // End of variables declaration//GEN-END:variables
}
