/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View.Rental.Component;

import Model.Car;
import java.awt.Image;
import java.io.File;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import View.Rental.SearchCarViewFrm;
import Controller.Rental.CartComponentController;
/**
 *
 * @author LEGION
 */
public class CartComponent extends javax.swing.JPanel {

    private Car car = new Car();
    private SearchCarViewFrm frame;

    /**
     * Creates new form CartComponent
     */
    public CartComponent() {
        initComponents();
    }

    public CartComponent(Car car, SearchCarViewFrm frame) {
        initComponents();
        this.frame = frame;
        this.car = car;
        this.nameLabel.setText(car.getName());
        this.priceLabel.setText(car.getPrice() + "");
        this.imageLabel.setText("");
        CartComponentController a = new CartComponentController(this);
        a.init();
        File file = new File("src/View/Rental/CarImage/" + car.getId() + ".jpg");
        if (file.exists()) {
            ImageIcon icon = new ImageIcon("src/View/Rental/CarImage/" + car.getId() + ".jpg");
            Image image = icon.getImage();
            Image newimg = image.getScaledInstance(93, 59, java.awt.Image.SCALE_SMOOTH);
            ImageIcon real = new ImageIcon(newimg);
            this.imageLabel.setIcon(real);
        } else {
            ImageIcon icon = new ImageIcon("src/View/Rental/CarImage/defaultcar.jpg");
            Image image = icon.getImage();
            Image newimg = image.getScaledInstance(93, 59, java.awt.Image.SCALE_SMOOTH);
            ImageIcon real = new ImageIcon(newimg);
            this.imageLabel.setIcon(real);
        }
        ImageIcon icon = new ImageIcon("src/View/Rental/Icon/delete_48px.png");
        Image image = icon.getImage();
        Image newimg = image.getScaledInstance(48, 48, java.awt.Image.SCALE_SMOOTH);
        ImageIcon real = new ImageIcon(newimg);
        this.exitLabel.setIcon(real);

    }

    public SearchCarViewFrm getFrame() {
        return frame;
    }

    public void setFrame(SearchCarViewFrm frame) {
        this.frame = frame;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nameLabel = new javax.swing.JLabel();
        priceLabel = new javax.swing.JLabel();
        imageLabel = new javax.swing.JLabel();
        exitLabel = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(32767, 470));
        setPreferredSize(new java.awt.Dimension(413, 60));

        nameLabel.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        nameLabel.setForeground(new java.awt.Color(51, 0, 204));
        nameLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nameLabel.setText("Name");

        priceLabel.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        priceLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        priceLabel.setText("Price");

        imageLabel.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        imageLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        imageLabel.setText("Image");

        exitLabel.setPreferredSize(new java.awt.Dimension(50, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(imageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(priceLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(exitLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(imageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(nameLabel)
                        .addComponent(priceLabel))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(exitLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(1, 1, 1))
        );
    }// </editor-fold>//GEN-END:initComponents

    public JLabel getImageLabel() {
        return imageLabel;
    }

    public void setImageLabel(JLabel imageLabel) {
        this.imageLabel = imageLabel;
    }

    public JLabel getNameLabel() {
        return nameLabel;
    }

    public void setNameLabel(JLabel nameLabel) {
        this.nameLabel = nameLabel;
    }

    public JLabel getPriceLabel() {
        return priceLabel;
    }

    public void setPriceLabel(JLabel priceLabel) {
        this.priceLabel = priceLabel;
    }

    public Car getCar() {
        return car;
    }

    public void setCar(Car car) {
        this.car = car;
    }

    public JLabel getExitLabel() {
        return exitLabel;
    }

    public void setExitLabel(JLabel exitLabel) {
        this.exitLabel = exitLabel;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel exitLabel;
    private javax.swing.JLabel imageLabel;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JLabel priceLabel;
    // End of variables declaration//GEN-END:variables
}
